// @generated by scripts/cheat-manifest.js; DO NOT EDIT.
import { runDiagnosticsCheat } from "../definitions/developer/run-diagnostics.cheat.js";
import { ballsCheat } from "../definitions/player/balls.cheat.js";
import { bodySizeCheat } from "../definitions/player/body-size.cheat.js";
import { bodyTypeCheat } from "../definitions/player/body-type.cheat.js";
import { characteristicsCheat } from "../definitions/player/characteristics.cheat.js";
import { crimeCheat } from "../definitions/player/crime.cheat.js";
import { cumCheat } from "../definitions/player/cum.cheat.js";
import { enemyStatsCheat } from "../definitions/player/enemy-stats.cheat.js";
import { examCheat } from "../definitions/player/exam.cheat.js";
import { fameCheat } from "../definitions/player/fame.cheat.js";
import { hentaiSkillCheat } from "../definitions/player/hentai-skill.cheat.js";
import { infiniteArousalCheat } from "../definitions/player/infinite-arousal.cheat.js";
import { lactationCheat } from "../definitions/player/lactation.cheat.js";
import { milkCheat } from "../definitions/player/milk.cheat.js";
import { moneyCheat } from "../definitions/player/money.cheat.js";
import { parasitesCheat } from "../definitions/player/parasites.cheat.js";
import { schoolReputationCheat } from "../definitions/player/school-reputation.cheat.js";
import { playerStatsCheat } from "../definitions/player/stats.cheat.js";
import { talentCheat } from "../definitions/player/talent.cheat.js";
import { unlimitedSprayCheat } from "../definitions/player/unlimited-spray.cheat.js";
import { virginityCheat } from "../definitions/player/virginity.cheat.js";
import { arousalCheat } from "../definitions/quick/arousal.cheat.js";
import { autoChildInteractionCheat } from "../definitions/quick/auto-child-interaction.cheat.js";
import { edenGardenCheat } from "../definitions/quick/eden-garden.cheat.js";
import { edenMushroomsCheat } from "../definitions/quick/eden-mushrooms.cheat.js";
import { edenSpringCheat } from "../definitions/quick/eden-spring.cheat.js";
import { edenTimerCheat } from "../definitions/quick/eden-timer.cheat.js";
import { enemyStateCheat } from "../definitions/quick/enemy-state.cheat.js";
import { everyoneHornyCheat } from "../definitions/quick/everyone-horny.cheat.js";
import { farmSafetyCheat } from "../definitions/quick/farm-safety.cheat.js";
import { gameCheatsCheat } from "../definitions/quick/game-cheats.cheat.js";
import { hygieneCheat } from "../definitions/quick/hygiene.cheat.js";
import { infiniteNpcPregnancyCheat } from "../definitions/quick/infinite-npc-pregnancy.cheat.js";
import { intenseCumCheat } from "../definitions/quick/intense-cum.cheat.js";
import { invincibleAngelCheat } from "../definitions/quick/invincible-angel.cheat.js";
import { maintainPurityCheat } from "../definitions/quick/maintain-purity.cheat.js";
import { maintainVirginityCheat } from "../definitions/quick/maintain-virginity.cheat.js";
import { maximumNpcPregnancyRateCheat } from "../definitions/quick/maximum-npc-pregnancy-rate.cheat.js";
import { maximumStrayTasksCheat } from "../definitions/quick/maximum-stray-tasks.cheat.js";
import { multipleNpcPregnanciesCheat } from "../definitions/quick/multiple-npc-pregnancies.cheat.js";
import { playerStateCheat } from "../definitions/quick/player-state.cheat.js";
import { pregnancyDetectionCheat } from "../definitions/quick/pregnancy-detection.cheat.js";
import { randomEncountersCheat } from "../definitions/quick/random-encounters.cheat.js";
import { templeVowCheat } from "../definitions/quick/temple-vow.cheat.js";
import { unlimitedCumCheat } from "../definitions/quick/unlimited-cum.cheat.js";
import { farmAnimalAffinityCheat } from "../definitions/world/farm-animal-affinity.cheat.js";
import { farmAssaultTimeCheat } from "../definitions/world/farm-assault-time.cheat.js";
import { farmBuildTimeCheat } from "../definitions/world/farm-build-time.cheat.js";
import { maxHarmonyCheat } from "../definitions/world/max-harmony.cheat.js";
import { maximumChurchTasksCheat } from "../definitions/world/maximum-church-tasks.cheat.js";
import { mcAbortionCheat } from "../definitions/world/mc-abortion.cheat.js";
import { mcChildManagerCheat } from "../definitions/world/mc-child-manager.cheat.js";
import { mcPregnancyCheat } from "../definitions/world/mc-pregnancy.cheat.js";
import { mcTentacleCheat } from "../definitions/world/mc-tentacle.cheat.js";
import { namedNpcAbortionCheat } from "../definitions/world/named-npc-abortion.cheat.js";
import { namedNpcPregnancyCheat } from "../definitions/world/named-npc-pregnancy.cheat.js";
import { npcTraitEditorCheat } from "../definitions/world/npc-trait-editor.cheat.js";
import { produceSalesReportCheat } from "../definitions/world/produce-sales-report.cheat.js";
import { storedNpcAbortionCheat } from "../definitions/world/stored-npc-abortion.cheat.js";
import { storedNpcPregnancyCheat } from "../definitions/world/stored-npc-pregnancy.cheat.js";
import { vrelCoinsUsageCheat } from "../definitions/world/vrel-coins-usage.cheat.js";

export const generatedCheats = Object.freeze([
  runDiagnosticsCheat,
  ballsCheat,
  bodySizeCheat,
  bodyTypeCheat,
  characteristicsCheat,
  crimeCheat,
  cumCheat,
  enemyStatsCheat,
  examCheat,
  fameCheat,
  hentaiSkillCheat,
  infiniteArousalCheat,
  lactationCheat,
  milkCheat,
  moneyCheat,
  parasitesCheat,
  schoolReputationCheat,
  playerStatsCheat,
  talentCheat,
  unlimitedSprayCheat,
  virginityCheat,
  arousalCheat,
  autoChildInteractionCheat,
  edenGardenCheat,
  edenMushroomsCheat,
  edenSpringCheat,
  edenTimerCheat,
  enemyStateCheat,
  everyoneHornyCheat,
  farmSafetyCheat,
  gameCheatsCheat,
  hygieneCheat,
  infiniteNpcPregnancyCheat,
  intenseCumCheat,
  invincibleAngelCheat,
  maintainPurityCheat,
  maintainVirginityCheat,
  maximumNpcPregnancyRateCheat,
  maximumStrayTasksCheat,
  multipleNpcPregnanciesCheat,
  playerStateCheat,
  pregnancyDetectionCheat,
  randomEncountersCheat,
  templeVowCheat,
  unlimitedCumCheat,
  farmAnimalAffinityCheat,
  farmAssaultTimeCheat,
  farmBuildTimeCheat,
  maxHarmonyCheat,
  maximumChurchTasksCheat,
  mcAbortionCheat,
  mcChildManagerCheat,
  mcPregnancyCheat,
  mcTentacleCheat,
  namedNpcAbortionCheat,
  namedNpcPregnancyCheat,
  npcTraitEditorCheat,
  produceSalesReportCheat,
  storedNpcAbortionCheat,
  storedNpcPregnancyCheat,
  vrelCoinsUsageCheat,
]);
